name: Deploy Docker
on:
  push:
    branches: [ "main" ] # Dispara o workflow quando houver um push na branch principal (você pode alterar)

permissions:
  pages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build and push Docker image
        run: |
          docker buildx build -t camileite/mriaas:${{secrets.GITHUB_TOKEN}} .
          docker push camileite/mriaas:${{secrets.GITHUB_TOKEN}} 